# Generated by Django 4.0 on 2022-03-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pizza_restaurant_delete_task_pizza_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
